[package]
name = "wled"
description = "A command-line-interface for WLED"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
reqwest = { version = "0.13.1", features = ["json", "blocking"] }
serde_json = "1.0.148"
